// Copyright Epic Games, Inc.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "GasXAttributeMetadata.generated.h"

/**
 * Row structure for AttributeMetadata DataTables.
 * 
 * WHY: Provides a designer-friendly way to edit attribute base values, min/max bounds,
 * and descriptions without touching C++ or JSON schemas. Generated by the AttributeSet
 * generator and consumed by bootstrap or initialization systems.
 */
USTRUCT(BlueprintType)
struct GASXRUNTIME_API FGasXAttributeMetadataRow : public FTableRowBase
{
	GENERATED_BODY()

public:
	/** Base/default value for this attribute */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attribute")
	double BaseValue = 0.0;

	/** Minimum allowed value (for UI clamping and validation) */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attribute")
	double MinValue = 0.0;

	/** Maximum allowed value (for UI clamping and validation) */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attribute")
	double MaxValue = 100.0;

	/** Designer-facing description of what this attribute represents */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Attribute")
	FString Description;
};
