// Copyright Epic Games, Inc.
// AUTO-GENERATED by GasXAttributeSetGenerator - DO NOT EDIT MANUALLY

#include "Attributes/PlayerCoreAttributes.h"
#include "Net/UnrealNetwork.h"

UPlayerCoreAttributes::UPlayerCoreAttributes()
{
	//GEN-BEGIN: Constructor Initialization
	Health.SetBaseValue(100.00f);
	Health.SetCurrentValue(100.00f);
	MaxHealth.SetBaseValue(100.00f);
	MaxHealth.SetCurrentValue(100.00f);
	Stamina.SetBaseValue(100.00f);
	Stamina.SetCurrentValue(100.00f);
	Mana.SetBaseValue(50.00f);
	Mana.SetCurrentValue(50.00f);
	//GEN-END: Constructor Initialization
}

//GEN-BEGIN: OnRep Implementations
void UPlayerCoreAttributes::OnRep_Health(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPlayerCoreAttributes, Health, OldValue);
}

void UPlayerCoreAttributes::OnRep_MaxHealth(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPlayerCoreAttributes, MaxHealth, OldValue);
}

void UPlayerCoreAttributes::OnRep_Stamina(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPlayerCoreAttributes, Stamina, OldValue);
}

void UPlayerCoreAttributes::OnRep_Mana(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPlayerCoreAttributes, Mana, OldValue);
}

//GEN-END: OnRep Implementations

void UPlayerCoreAttributes::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	//GEN-BEGIN: Replication Setup
	DOREPLIFETIME_CONDITION_NOTIFY(UPlayerCoreAttributes, Health, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UPlayerCoreAttributes, MaxHealth, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UPlayerCoreAttributes, Stamina, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UPlayerCoreAttributes, Mana, COND_None, REPNOTIFY_Always);
	//GEN-END: Replication Setup
}
