// Copyright Epic Games, Inc.
// AUTO-GENERATED by GasXAttributeSetGenerator - DO NOT EDIT MANUALLY

#include "Attributes/PrimaryAttributes.h"
#include "Net/UnrealNetwork.h"

UPrimaryAttributes::UPrimaryAttributes()
{
	//GEN-BEGIN: Constructor Initialization
	Health.SetBaseValue(100.00f);
	Health.SetCurrentValue(100.00f);
	MaxHealth.SetBaseValue(100.00f);
	MaxHealth.SetCurrentValue(100.00f);
	Mana.SetBaseValue(50.00f);
	Mana.SetCurrentValue(50.00f);
	//GEN-END: Constructor Initialization
}

//GEN-BEGIN: OnRep Implementations
void UPrimaryAttributes::OnRep_Health(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPrimaryAttributes, Health, OldValue);
}

void UPrimaryAttributes::OnRep_MaxHealth(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPrimaryAttributes, MaxHealth, OldValue);
}

void UPrimaryAttributes::OnRep_Mana(const FGameplayAttributeData& OldValue)
{
	GAMEPLAYATTRIBUTE_REPNOTIFY(UPrimaryAttributes, Mana, OldValue);
}

//GEN-END: OnRep Implementations

void UPrimaryAttributes::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	//GEN-BEGIN: Replication Setup
	DOREPLIFETIME_CONDITION_NOTIFY(UPrimaryAttributes, Health, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UPrimaryAttributes, MaxHealth, COND_None, REPNOTIFY_Always);
	DOREPLIFETIME_CONDITION_NOTIFY(UPrimaryAttributes, Mana, COND_None, REPNOTIFY_Always);
	//GEN-END: Replication Setup
}
