// Copyright Epic Games, Inc.
// AUTO-GENERATED by GasXAttributeSetGenerator - DO NOT EDIT MANUALLY

#pragma once

#include "CoreMinimal.h"
#include "AttributeSet.h"
#include "AbilitySystemComponent.h"
#include "PlayerCoreAttributes.generated.h"

/**
 * Generated AttributeSet: PlayerCoreAttributes
 * Core player attributes: Health, Stamina, and Mana
 */
UCLASS()
class GASXRUNTIME_API UPlayerCoreAttributes : public UAttributeSet
{
	GENERATED_BODY()

public:
	UPlayerCoreAttributes();

//GEN-BEGIN: Attribute Properties
	/** Current health points */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Health)
	FGameplayAttributeData Health;

	/** Maximum health capacity */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_MaxHealth)
	FGameplayAttributeData MaxHealth;

	/** Current stamina points for sprint/dodge actions */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Stamina)
	FGameplayAttributeData Stamina;

	/** Current mana for abilities */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Mana)
	FGameplayAttributeData Mana;

	/** Current energy for abilities */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Energy)
	FGameplayAttributeData Energy;

	//GEN-END: Attribute Properties

//GEN-BEGIN: Attribute Accessors
	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPlayerCoreAttributes, Health)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Health)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Health)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Health)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPlayerCoreAttributes, MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(MaxHealth)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPlayerCoreAttributes, Stamina)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Stamina)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Stamina)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Stamina)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPlayerCoreAttributes, Mana)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Mana)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Mana)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Mana)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPlayerCoreAttributes, Energy)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Energy)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Energy)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Energy)

	//GEN-END: Attribute Accessors

//GEN-BEGIN: OnRep Functions
	UFUNCTION()
	virtual void OnRep_Health(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxHealth(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Stamina(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Mana(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Energy(const FGameplayAttributeData& OldValue);

	//GEN-END: OnRep Functions

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty> &OutLifetimeProps) const override;
};
