// Copyright Epic Games, Inc.
// AUTO-GENERATED by GasXAttributeSetGenerator - DO NOT EDIT MANUALLY

#pragma once

#include "CoreMinimal.h"
#include "AttributeSet.h"
#include "AbilitySystemComponent.h"
#include "PrimaryAttributes.generated.h"

/**
 * Generated AttributeSet: PrimaryAttributes
 * Core player attributes: Health  and Mana
 */
UCLASS()
class GASXRUNTIME_API UPrimaryAttributes : public UAttributeSet
{
	GENERATED_BODY()

public:
	UPrimaryAttributes();

	//GEN-BEGIN: Attribute Properties
	/** Current health points */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Health)
	FGameplayAttributeData Health;

	/** Maximum health capacity */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_MaxHealth)
	FGameplayAttributeData MaxHealth;

	/** Current mana for abilities */
	UPROPERTY(BlueprintReadOnly, Category="Attributes", ReplicatedUsing=OnRep_Mana)
	FGameplayAttributeData Mana;

	//GEN-END: Attribute Properties

	//GEN-BEGIN: Attribute Accessors
	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPrimaryAttributes, Health)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Health)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Health)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Health)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPrimaryAttributes, MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(MaxHealth)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(MaxHealth)

	GAMEPLAYATTRIBUTE_PROPERTY_GETTER(UPrimaryAttributes, Mana)
	GAMEPLAYATTRIBUTE_VALUE_GETTER(Mana)
	GAMEPLAYATTRIBUTE_VALUE_SETTER(Mana)
	GAMEPLAYATTRIBUTE_VALUE_INITTER(Mana)

	//GEN-END: Attribute Accessors

	//GEN-BEGIN: OnRep Functions
	UFUNCTION()
	virtual void OnRep_Health(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_MaxHealth(const FGameplayAttributeData& OldValue);

	UFUNCTION()
	virtual void OnRep_Mana(const FGameplayAttributeData& OldValue);

	//GEN-END: OnRep Functions

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
};
